add_newline = false

format = """$directory$git_branch$git_status$character"""
right_format = """$all"""

[directory]
truncation_length = 8
truncation_symbol = '…/'
style = 'bold #add7ff'
format = '[$path]($style)[$read_only]($read_only_style) '

[cmd_duration]
style = 'bold #f087bd'
format = '[$duration]($style) '

[git_branch]
symbol = ' '
style = 'bold #5de4c7'
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = 'bold #f087bd'
format = '[$all_status$ahead_behind]($style) '

[git_metrics]
disabled = true

[character]
success_symbol = '[❯](#5de4c7)'
error_symbol = '[❯](#f087bd)'

[cmake]
symbol = ' '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[conda]
symbol = ' '
style = 'bold blue'
ignore_base = false
format = '[$symbol$environment]($style) '

[python]
disabled = true

[lua]
symbol = ' '
format = '[$symbol($version )]($style) '
disabled = true

[rust]
symbol = '󱘗'
style = 'bold blue'
version_format = '${raw}'
format = '[$symbol ($version)]($style) '
disabled = true

[c]
symbol = ' '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[vlang]
symbol = ' '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[java]
symbol = ' '
style = 'bold red'
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[nodejs]
symbol = '' 
style = 'bold green'
version_format = '${raw}'
format = '[$symbol ($version)]($style) '
disabled = false

[package]
symbol = '󰏗 '
style = 'bold blue'
version_format = '${raw} '
format = '[$symbol$version]($style) '

