add_newline = false

# LEFT PROMPT
format = """$directory$git_branch$git_status$character"""

# Move rest of the prompt to the right
right_format = """$all"""


# DIRECTORY
[directory]
truncation_length = 8
truncation_symbol = '…/'

# [directory.substitutions]
# '~/Development/C++/DS-SEM3' = 'DSA'

# DURATION
[cmd_duration]
style = 'bold yellow'
format = '[$duration]($style) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = 'bold red'
format = '[$all_status$ahead_behind]($style) '

# DISPLAY: +34 -12
[git_metrics]
disabled = true 

[cmake]
symbol = ' '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[conda]
symbol = ' '
style = 'bold blue'
ignore_base = false
format = '[$symbol$environment]($style) '

[python]
disabled = true

[lua]
symbol = ' '
format = '[$symbol($version )]($style) '
disabled = true

[rust]
symbol = '󱘗'
style = 'bold blue'
version_format = '${raw}'
format = '[$symbol ($version)]($style) '
disabled = true

[c]
symbol = ' '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[vlang]
symbol = ' '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[java]
symbol = ' '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[nodejs]
symbol = '' 
style = 'bold green'
version_format = '${raw}'
format = '[$symbol ($version)]($style) '
disabled = false

[package]
symbol = '󰏗 '
style = 'bold blue'
version_format = '${raw} '
format = '[$symbol$version]($style) '
